clear;clc;
t=0:0.001:1;
vm=15;
vc=10;
fm=10;
fc=100;
m=vm*sin(2*pi*fm*t);
c=vc*sin(2*pi*fc*t);
amp=vc+vm*sin(2*pi*fm*t);
s=amp.*sin(2*pi*fc*t);
s1=amp.*cos(2*pi*(fc*fm)*t);
subplot(4,1,1);
plot(t,m);
xlabel('Time(sec)');
ylabel('amplitude(volts)');
title('Message signal');
subplot(4,1,2);
plot(t,c);
xlabel('Time(sec)');
ylabel('Amplitude(volts)');
title('Carrier signal');
subplot(4,1,3);
plot(t,s);
xlabel('Time(sec)');
ylabel('Amplitude(volts)');
title('Amplitude modulation');
subplot(4,1,4);
plot(t,s1);
xlabel('Time(sec)');
ylabel('Amplitude(volts)');
title('Amplitude Demodulation');
