fm=25;
fc=400;
mf=10;
t=0:0.0001:0.1;
m=sin(2*pi*fm*t);
subplot(3,1,1);
plot(t,m);
xlabel('Time(s)');
ylabel('Amplitude(V)');
title('Message Signal');
c=sin(2*pi*fc*t);
subplot(3,1,2);
plot(t,c);
xlabel('Time(s)');
ylabel('Amplitude(V)');
title('Carrier Signal');
y=sin(2*pi*fc*t+(mf.*sin(2*pi*fm*t)));%Frequency changing w.r.t Message signal
subplot(3,1,3);
plot(t,y);
xlabel('Time(s)');
ylabel('Amplitude(V)');
title('Frequency modulated Signal');